services:
  proxy: 
    image: alfg/nginx-rtmp
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
      - 80:80
  
  http:
    container_name: http
    build: ./http
    ports:
      - 5000:5000
    restart: "on-failure"

  app:
    build: ./app
    ports:
      - 3000:3000
    restart: "on-failure"
    depends_on:
      - http
      - proxy